DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS DEPARTMENT;

CREATE TABLE EMPLOYEE (
  ID INT NOT NULL AUTO_INCREMENT
, DEPARTMENT_ID INT
, FIRST_NAME VARCHAR(35) NOT NULL
, LAST_NAME VARCHAR(35) NOT NULL
, SALARY INT
);

CREATE TABLE DEPARTMENT (
  ID INT NOT NULL AUTO_INCREMENT
, NAME VARCHAR(99) NOT NULL
, AVG_SALARY INT
);